[build]
  publish = "."
  command = "echo 'Static site ready'"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Webhook endpoint - preserve raw body for signature verification
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Admin panel protection
[[headers]]
  for = "/admin*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Audiobook player protection  
[[headers]]
  for = "/audiobook-player*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
