backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://aleksfilmore.com
display_url: https://aleksfilmore.com

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: true
        default: ""
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Aleks Filmore"
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Content"
            name: "body"
            widget: "markdown"
      
      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Content"
            name: "body"
            widget: "markdown"

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "data/settings.json"
        fields:
          - label: "Site Title"
            name: "title"
            widget: "string"
            default: "Aleks Filmore"
          - label: "Site Description"
            name: "description"
            widget: "text"
            default: "Author of The Worst Boyfriends Ever"
          - label: "Site URL"
            name: "url"
            widget: "string"
            default: "https://aleksfilmore.com"
          - label: "Author Email"
            name: "email"
            widget: "string"
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - label: "Instagram"
                name: "instagram"
                widget: "string"
                required: false
              - label: "TikTok"
                name: "tiktok"
                widget: "string"
                required: false
              - label: "Spotify"
                name: "spotify"
                widget: "string"
                required: false
      
      - label: "Product Settings"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Audiobook Price"
            name: "audiobook_price"
            widget: "number"
            value_type: "float"
            default: 7.99
          - label: "Signed Book Price"
            name: "book_price"
            widget: "number"
            value_type: "float"
            default: 19.99
          - label: "Bundle Price"
            name: "bundle_price"
            widget: "number"
            value_type: "float"
            default: 24.99
          - label: "Shipping Enabled"
            name: "shipping_enabled"
            widget: "boolean"
            default: true
          - label: "Audiobook Available"
            name: "audiobook_available"
            widget: "boolean"
            default: true
